# Generated by Django 3.1.7 on 2021-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210401_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Country',
            field=models.TextField(default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
